Script para ignorar arquivos de build rastreados pelo git
GLR21/autom_V3 pull request #58
Opened 2023-10-30 22:56 UTC by SamuelUniverso

Esse arquivo realiza o comando "git update-index --assume-unchanged" em arquivos que já são rastreados.
É uma forma simples para que o git pare de mapear esses arquivos, mesmo que eles estejam commitados na tree.

2023-10-30 23:00 UTC, GLR21 requested changes
Não era só adicionar no .gitignore, por exemplo: window/* linux/* e assim por diante? O que esse comando que tu commitou faz?

2023-10-30 23:09 UTC, SamuelUniverso commented
.gitignore apenas funciona para arquivos untracked.

Esses arquivos de build já estão sendo mapeados pelo git (tracked) e por isso colocar essas pastas  window/* linux/* no gitgnore não surte nenhum efeito.

Esses arquivos apenas começariam a ser ignorados pelo .gitignore se eles fossem deletados da tree. Pelos testes que fiz isso não é uma opção porque a build dos projetos começa a falhar. Esses arquivos são necessários para a build funcionar.

A forma que encontrei de fazer o git ignorar arquivos que **já estão mapeados** (ignorar updates nesses arquivos) é usando o comando `git update-index --assume-unanged `

Fonte:
https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

2023-10-30 23:26 UTC, GLR21 commented
Certo @SamuelUniverso , entendo que isso seria apenas para o repositório local?

2023-10-30 23:31 UTC, SamuelUniverso commented
Sim, apenas local

2023-10-31 00:12 UTC, GLR21 commented
Certo. Então deixa assim @SamuelUniverso , seguimos com as outras demandas mais críticas. Login, principalmente e relatório, to fechand a pull aqui.

2023-10-31 00:12 UTC, closed without merging